<body>
<h1>Films</h1>
<hr>
<tr>
    <form method="post" action="../webroot/index.php?controller=default&action=add">
        <td><p>Добавить фильм </p><input type="hidden" name="id" ></td>
        <td><input type="text" name="title" > </td>
        <td><input type="text" name="release_year" > </td>
        <td><input type="text" name="format" >
        </td>
        <td><input type="text" name="stars" >
        </td>
        <td>
            <button>Save</button>
        </td>
    </form>
</tr>

<form method="post" action="../webroot/index.php?controller=default&action=sort">
    <select name="sort_by" size="1">
       <option value="sort_by_name">sort_by_name</option>
    </select>
    <button>select</button>
</form>


<form method="post" action="../webroot/index.php?controller=default&action=find">
    <p>Найти по названию фильма или актера </p> <input type="text" name="find">
        <button>find</button>
</form>


<?=$content?>
</body>